name: Blueprint Engine
version: "0.1.0"
slug: blueprint_engine
description: The heavy processing engine for HA 3D Blueprint.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: default
# The user will need to have the InfluxDB add-on running.
services:
  - "47c55538-influxdbv2:want"
image: "ghcr.io/delicioushouse/{arch}-addon-blueprint-engine"
ports:
  "8124/tcp": 8124 # Port for the internal API
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  # InfluxDB v2 Configuration
  influxdb_url: str
  influxdb_token: password
  influxdb_org: str
  influxdb_bucket: str
