name: Blueprint Engine
version: "0.1.0"
slug: blueprint_engine
description: The heavy processing engine for HA 3D Blueprint.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: default
# image: null # Correct for local development

# This block exposes the port from the add-on's container
ports:
  "8124/tcp": 8124

# This block sets the default values for your options
options:
  port: 8124
  log_level: "info"
  influxdb_url: "http://47c55538-influxdbv2:8086"
  influxdb_token: ""
  influxdb_org: ""
  influxdb_bucket: ""

# This block defines the UI controls for the options
schema:
  port: int
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  influxdb_url: str
  influxdb_token: password
  influxdb_org: str
  influxdb_bucket: str